name: Auto-Build-And-Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: dev
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  nestjs-build:
    name: Build NestJS App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  test:
    name: Test NestJS App
    runs-on: ubuntu-latest
    needs: nestjs-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test
